spring:
  application:
    name: providers
dubbo:
  scan:
    base-packages: com.fengqi.providers.service
  protocol:
    name: dubbo
    port: 9010
  registry:
    address: zookeeper://39.105.132.36:${embedded.zookeeper.port}
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
server:
  port: 8282
demo:
  service:
    version: 1.0.0
embedded:
  zookeeper:
    port: 2181